In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/processed/sales_cleaned.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,01-01-2022,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,01-01-2022,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,01-01-2022,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,01-01-2022,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,01-01-2022,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [4]:
df["original_revenue"] = df["Price"] * df["Units Sold"]

In [6]:
def adjust_price(row):

    price = row["Price"]

    # Inventory rule
    if row["Inventory Level"] < 20:
        price = price * 1.15

    elif row["Inventory Level"] > 100:
        price = price * 0.90

    # Demand rule
    if row["Units Sold"] > 50:
        price = price * 1.10

    elif row["Units Sold"] < 20:
        price = price * 0.95

    return price

In [7]:
df["adjusted_price"] = df.apply(adjust_price, axis=1)

In [9]:
df[["Price","adjusted_price"]].head()

   Price  adjusted_price
0  33.50         33.1650
1  63.01         62.3799
2  27.99         27.7101
3  32.72         32.3928
4  73.64         62.9622

In [10]:
df["new_revenue"] = df["adjusted_price"] * df["Units Sold"]

In [11]:
original_revenue = df["original_revenue"].sum()
new_revenue = df["new_revenue"].sum()

print("Original Revenue:", original_revenue)
print("New Revenue:", new_revenue)

Original Revenue: 550228884.9100001
New Revenue: 543989475.7977

In [15]:
revenue_lift = abs((new_revenue - original_revenue) / original_revenue) * 100

print("Revenue Lift (%):", round(revenue_lift, 2))

Revenue Lift (%): 1.13